import 'dotenv/config';

const dbPort = process.env.DB_PORT?.trim() ? Number(process.env.DB_PORT) : null;

export const env = {
  nodeEnv: process.env.NODE_ENV || 'development',
  port: Number(process.env.PORT || 4000),
  corsOrigin: process.env.CORS_ORIGIN || '*',
  dbHost: process.env.DB_HOST || 'localhost',
  dbPort,
  dbName: process.env.DB_NAME || 'huyperfume',
  dbUser: process.env.DB_USER || '',
  dbPassword: process.env.DB_PASSWORD || '',
  dbDriver: process.env.DB_DRIVER || 'ODBC Driver 18 for SQL Server',
  jwtSecret: process.env.JWT_SECRET || 'change-me-in-production',
  jwtExpirationMs: Number(process.env.JWT_EXPIRATION_MS || 86400000),
  refreshTokenExpirationMs: Number(process.env.REFRESH_TOKEN_EXPIRATION_MS || 604800000),
  passwordResetTokenExpirationMs: Number(process.env.PASSWORD_RESET_TOKEN_EXPIRATION_MS || 900000),
  emailVerificationTokenExpirationMs: Number(process.env.EMAIL_VERIFICATION_TOKEN_EXPIRATION_MS || 86400000),
  bcryptRounds: Number(process.env.BCRYPT_ROUNDS || 12),
  authRateLimitWindowMs: Number(process.env.AUTH_RATE_LIMIT_WINDOW_MS || 60000),
  authRateLimitMax: Number(process.env.AUTH_RATE_LIMIT_MAX || 20),
  loginFailureLimit: Number(process.env.LOGIN_FAILURE_LIMIT || 5),
  loginFailureWindowMs: Number(process.env.LOGIN_FAILURE_WINDOW_MS || 900000),
  loginLockMs: Number(process.env.LOGIN_LOCK_MS || 900000),
  captchaExpirationMs: Number(process.env.CAPTCHA_EXPIRATION_MS || 300000),
  captchaLoginFailureThreshold: Number(process.env.CAPTCHA_LOGIN_FAILURE_THRESHOLD || 3),
  captchaSecret: process.env.CAPTCHA_SECRET || process.env.JWT_SECRET || 'change-me-in-production',
  authExposeDevTokens: String(process.env.AUTH_EXPOSE_DEV_TOKENS || (process.env.NODE_ENV === 'production' ? 'false' : 'true')).toLowerCase() === 'true',
  redisUrl: process.env.REDIS_URL || '',
  productCacheTtlSeconds: Number(process.env.PRODUCT_CACHE_TTL_SECONDS || 300),
  checkoutReservationTtlSeconds: Number(process.env.CHECKOUT_RESERVATION_TTL_SECONDS || 900),
  checkoutLockTtlMs: Number(process.env.CHECKOUT_LOCK_TTL_MS || 10000),
  lowStockThreshold: parseInt(process.env.LOW_STOCK_THRESHOLD || '5', 10),
};
