apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: huyperfume

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  - path: configmap-patch.yaml
  - path: replica-count.yaml
  - path: resource-limits.yaml
