apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huyperfume
  namespace: huyperfume
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/gzip-types: "application/javascript application/json text/css image/svg+xml"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - huyperfume.com
        - www.huyperfume.com
      secretName: huyperfume-tls
  rules:
    - host: huyperfume.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
