apiVersion: v1
kind: ConfigMap
metadata:
  name: huyperfume-config
data:
  NODE_ENV: "staging"
  CORS_ORIGIN: "https://staging.huyperfume.com"
  AUTH_EXPOSE_DEV_TOKENS: "true"
  PRODUCT_CACHE_TTL_SECONDS: "120"
  CHECKOUT_RESERVATION_TTL_SECONDS: "600"
  APP_BASE_URL: "https://staging.huyperfume.com"
  RUN_MIGRATIONS: "true"
