apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: huyperfume

resources:
  - ../../base

nameSuffix: -staging

commonLabels:
  environment: staging

patches:
  - path: configmap-patch.yaml
  - path: replica-count.yaml
